import { type DiscoverableCreator } from "../../../components/dashboard/types";

export const NICHE_OPTIONS = [
  "All",
  "Beauty",
  "Skincare",
  "Lifestyle",
  "Fitness",
  "Culture",
  "Storytelling",
  "Wellness",
];

export const MOCK_CREATORS: DiscoverableCreator[] = [
  {
    id: "cr1",
    name: "Temitope Adeyemi",
    avatar: "TA",
    color: "#a78bfa",
    location: "Lagos, Nigeria",
    niche: ["Beauty", "Lifestyle"],
    bio: "Authentic beauty creator documenting real skincare journeys for Nigerian women.",
    platforms: [
      { name: "Instagram", handle: "@temi.creates", followers: 24500 },
      { name: "TikTok", handle: "@temitope.adeyemi", followers: 18200 },
    ],
    totalFollowers: 42700,
    avgEngagement: 6.9,
    completedCampaigns: 8,
    rating: 4.8,
    priceRange: "$800–$1,500",
  },
  {
    id: "cr2",
    name: "Adaeze Obi",
    avatar: "AO",
    color: "#f97316",
    location: "Abuja, Nigeria",
    niche: ["Skincare", "Wellness"],
    bio: "Skincare educator with a science background. Evidence-based beauty content.",
    platforms: [
      { name: "Instagram", handle: "@adaeze.glows", followers: 38000 },
    ],
    totalFollowers: 38000,
    avgEngagement: 7.4,
    completedCampaigns: 14,
    rating: 4.9,
    priceRange: "$1,200–$2,500",
  },
  {
    id: "cr3",
    name: "Chisom Eze",
    avatar: "CE",
    color: "#60a5fa",
    location: "Lagos, Nigeria",
    niche: ["Beauty", "Fashion"],
    bio: "TikTok-first beauty creator. Fast editing, high energy, highly converting content.",
    platforms: [
      { name: "TikTok", handle: "@chisombeauty", followers: 91000 },
      { name: "Instagram", handle: "@chisom.eze", followers: 21000 },
    ],
    totalFollowers: 112000,
    avgEngagement: 8.1,
    completedCampaigns: 22,
    rating: 4.7,
    priceRange: "$2,000–$4,000",
  },
  {
    id: "cr4",
    name: "Funmi Balogun",
    avatar: "FB",
    color: "#f43f5e",
    location: "Port Harcourt, Nigeria",
    niche: ["Lifestyle", "Beauty"],
    bio: "Lifestyle creator with a hyper-engaged micro audience. Known for honest reviews.",
    platforms: [{ name: "Instagram", handle: "@funmi.b", followers: 12400 }],
    totalFollowers: 12400,
    avgEngagement: 9.2,
    completedCampaigns: 5,
    rating: 4.6,
    priceRange: "$400–$900",
  },
  {
    id: "cr5",
    name: "Emeka Nwosu",
    avatar: "EN",
    color: "#22c55e",
    location: "Lagos, Nigeria",
    niche: ["Culture", "Storytelling"],
    bio: "Long-form storyteller and brand narrator. My threads go viral. Consistently.",
    platforms: [
      { name: "Instagram", handle: "@emeka.tells", followers: 28000 },
      { name: "Twitter", handle: "@emekanwosu", followers: 14000 },
    ],
    totalFollowers: 42000,
    avgEngagement: 5.8,
    completedCampaigns: 11,
    rating: 4.9,
    priceRange: "$500–$1,200",
  },
  {
    id: "cr6",
    name: "Zara Okafor",
    avatar: "ZO",
    color: "#e879f9",
    location: "Enugu, Nigeria",
    niche: ["Fitness", "Wellness"],
    bio: "Certified PT and content creator. Fitness, health and sustainable beauty.",
    platforms: [
      { name: "Instagram", handle: "@zarafit", followers: 19800 },
      { name: "YouTube", handle: "Zara Okafor Fit", followers: 8400 },
    ],
    totalFollowers: 28200,
    avgEngagement: 7.1,
    completedCampaigns: 7,
    rating: 4.5,
    priceRange: "$600–$1,400",
  },
];
