import type { BrandCampaign } from "../../../components/dashboard/types";

export const MOCK_BRAND_CAMPAIGNS: BrandCampaign[] = [
  {
    id: "bc1",
    title: "Botanical Serum Launch",
    description:
      "Drive awareness and conversions for our new Vitamin C + Hibiscus serum targeting Gen Z skincare enthusiasts.",
    brief:
      "We're launching the Lush Botanics Vitamin C + Hibiscus Brightening Serum. We need creators to produce authentic unboxing content, 30-day transformation posts, and honest review-style videos. Tone should be warm, educational, and aspirational — not overly commercial.",
    status: "active",
    budget: 8500,
    budgetSpent: 4200,
    startDate: "2026-03-01",
    endDate: "2026-04-30",
    platforms: ["Instagram", "TikTok"],
    targetNiches: ["Beauty", "Skincare", "Lifestyle"],
    deliverables: [
      "2× Instagram Reels per creator",
      "1× TikTok video",
      "3× Stories",
    ],
    requirements: [
      "Min. 10K followers",
      "Nigerian audience preferred",
      "Skincare niche",
      "Female 18–35 demographic",
    ],
    applicationsCount: 18,
    creatorsHired: 4,
    analytics: {
      impressions: 248000,
      reach: 184000,
      clicks: 9600,
      conversions: 720,
      engagementRate: 6.8,
      roi: 142,
      weeklyData: [
        { day: "Mon", impressions: 28000, clicks: 980, conversions: 72 },
        { day: "Tue", impressions: 35000, clicks: 1240, conversions: 94 },
        { day: "Wed", impressions: 31000, clicks: 1080, conversions: 81 },
        { day: "Thu", impressions: 42000, clicks: 1560, conversions: 118 },
        { day: "Fri", impressions: 56000, clicks: 2100, conversions: 162 },
        { day: "Sat", impressions: 38000, clicks: 1440, conversions: 108 },
        { day: "Sun", impressions: 18000, clicks: 1200, conversions: 85 },
      ],
    },
  },
  {
    id: "bc2",
    title: "Hydration Range — Summer Push",
    description:
      "Summer awareness campaign for our shea butter hydration range across lifestyle and fitness creators.",
    brief:
      "The Summer Hydration campaign should feel fresh, sun-drenched, and aspirational. Creators should weave the product into their summer routines — pool days, post-gym, morning skincare. Focus on texture, scent, and the feeling of healthy skin.",
    status: "draft",
    budget: 5000,
    budgetSpent: 0,
    startDate: "2026-05-01",
    endDate: "2026-06-30",
    platforms: ["Instagram", "YouTube"],
    targetNiches: ["Lifestyle", "Fitness", "Health"],
    deliverables: ["1× YouTube review", "2× Instagram Reels", "4× Stories"],
    requirements: [
      "Min. 15K followers",
      "Lifestyle or fitness niche",
      "Engagement rate above 4%",
    ],
    applicationsCount: 0,
    creatorsHired: 0,
    analytics: {
      impressions: 0,
      reach: 0,
      clicks: 0,
      conversions: 0,
      engagementRate: 0,
      roi: 0,
      weeklyData: [],
    },
  },
  {
    id: "bc3",
    title: "Founder Story Series",
    description:
      "Long-form storytelling campaign spotlighting the brand's origin and values through micro-influencers.",
    brief:
      "We want 5 micro-influencers to tell the Lush Botanics origin story in their own voice. This isn't a product push — it's about brand values, African botanical heritage, and sustainability. Authenticity over aesthetics.",
    status: "completed",
    budget: 3200,
    budgetSpent: 3200,
    startDate: "2026-01-10",
    endDate: "2026-02-28",
    platforms: ["Instagram", "Twitter"],
    targetNiches: ["Storytelling", "Beauty", "Culture"],
    deliverables: ["1× Instagram carousel", "1× Twitter thread", "2× Stories"],
    requirements: ["Micro-influencer (5K–50K)", "Strong narrative voice"],
    applicationsCount: 31,
    creatorsHired: 5,
    analytics: {
      impressions: 412000,
      reach: 290000,
      clicks: 18400,
      conversions: 1380,
      engagementRate: 8.2,
      roi: 198,
      weeklyData: [
        { day: "Mon", impressions: 48000, clicks: 2100, conversions: 158 },
        { day: "Tue", impressions: 62000, clicks: 2800, conversions: 210 },
        { day: "Wed", impressions: 55000, clicks: 2420, conversions: 182 },
        { day: "Thu", impressions: 71000, clicks: 3200, conversions: 241 },
        { day: "Fri", impressions: 84000, clicks: 3900, conversions: 294 },
        { day: "Sat", impressions: 59000, clicks: 2600, conversions: 196 },
        { day: "Sun", impressions: 33000, clicks: 1380, conversions: 99 },
      ],
    },
  },
  {
    id: "bc4",
    title: "Back-to-School Glow Kit",
    description:
      "Target university students with a budget-friendly glow kit bundle across TikTok and Instagram.",
    brief:
      "The Glow Kit is priced for students. We want real, relatable content — dorm room lighting, morning routines, unboxings with genuine reactions. UGC-style preferred.",
    status: "paused",
    budget: 2400,
    budgetSpent: 800,
    startDate: "2026-02-01",
    endDate: "2026-03-31",
    platforms: ["TikTok", "Instagram"],
    targetNiches: ["Student", "Beauty", "Lifestyle"],
    deliverables: ["2× TikTok videos", "1× Instagram Reel"],
    requirements: ["18–24 demographic", "Student lifestyle content"],
    applicationsCount: 12,
    creatorsHired: 2,
    analytics: {
      impressions: 68000,
      reach: 51000,
      clicks: 2800,
      conversions: 196,
      engagementRate: 5.1,
      roi: 89,
      weeklyData: [
        { day: "Mon", impressions: 9000, clicks: 380, conversions: 27 },
        { day: "Tue", impressions: 11000, clicks: 460, conversions: 32 },
        { day: "Wed", impressions: 8500, clicks: 340, conversions: 24 },
        { day: "Thu", impressions: 14000, clicks: 600, conversions: 44 },
        { day: "Fri", impressions: 16000, clicks: 680, conversions: 47 },
        { day: "Sat", impressions: 9500, clicks: 340, conversions: 22 },
      ],
    },
  },
];
