import type { Project } from "../../../components/dashboard/types";

// ─── Projects ───────────────────────────────────────────────────────
export const MOCK_PROJECTS: Project[] = [
  {
    id: "p1",
    brand: "Aura Coffee",
    brandLogo: "AC",
    brandColor: "#a78bfa",
    category: "Food & Beverage",
    description: "Morning routine cold brew integration campaign.",
    budget: 600,
    amountEarned: 600,
    startDate: "2026-03-01",
    endDate: "2026-04-15",
    progress: 80,
    status: "active",
    platforms: ["Instagram"],
    deliverables: [
      { id: "d1", label: "Instagram Reel posted", done: true },
      { id: "d2", label: "Story 1 posted", done: true },
      { id: "d3", label: "Story 2 posted", done: false },
    ],
    analytics: { views: 14200, clicks: 980, conversions: 73, engagement: 6.9 },
  },
  {
    id: "p2",
    brand: "SolarWave Tech",
    brandLogo: "SW",
    brandColor: "#fbbf24",
    category: "Technology",
    description: "Product launch review for the SolarWave portable charger.",
    budget: 1800,
    amountEarned: 900,
    startDate: "2026-02-15",
    endDate: "2026-04-01",
    progress: 50,
    status: "in_review",
    platforms: ["YouTube", "Instagram"],
    deliverables: [
      { id: "d4", label: "YouTube review published", done: true },
      { id: "d5", label: "Instagram post live", done: false },
      { id: "d6", label: "Final report submitted", done: false },
    ],
    analytics: {
      views: 22800,
      clicks: 1540,
      conversions: 112,
      engagement: 5.2,
    },
  },
  {
    id: "p3",
    brand: "GlowUp Beauty",
    brandLogo: "GB",
    brandColor: "#ec4899",
    category: "Beauty",
    description: "Full 30-day skincare transformation campaign.",
    budget: 3000,
    amountEarned: 3000,
    startDate: "2026-01-10",
    endDate: "2026-02-28",
    progress: 100,
    status: "completed",
    platforms: ["Instagram", "TikTok"],
    deliverables: [
      { id: "d7", label: "Week 1 Reel", done: true },
      { id: "d8", label: "Week 2 Reel", done: true },
      { id: "d9", label: "Final transformation post", done: true },
      { id: "d10", label: "TikTok video", done: true },
    ],
    analytics: {
      views: 48000,
      clicks: 3200,
      conversions: 280,
      engagement: 8.4,
    },
  },
];
