import type { AppNotification } from "../../../components/dashboard/types";

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: "n1",
    type: "campaign_invite",
    title: "New Campaign Invite",
    body: "Lush Botanics has invited you to their Botanical Serum Launch campaign.",
    timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    read: false,
    actionPath: "/campaigns",
    avatarInitials: "LB",
    avatarColor: "#4ade80",
  },
  {
    id: "n2",
    type: "payment",
    title: "Payment Received",
    body: "GlowUp Beauty has sent a payout of $3,000 for the completed campaign.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    read: false,
    actionPath: "/transactions",
    avatarInitials: "GB",
    avatarColor: "#ec4899",
  },
  {
    id: "n3",
    type: "approval",
    title: "Application Approved",
    body: "Your application for the FitFlow Apparel campaign has been approved.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    read: false,
    actionPath: "/projects",
    avatarInitials: "FF",
    avatarColor: "#f97316",
  },
  {
    id: "n4",
    type: "reminder",
    title: "Deadline Approaching",
    body: "Your deliverable for Aura Coffee is due in 2 days. Don't miss it!",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    read: true,
    actionPath: "/projects",
    avatarInitials: "AC",
    avatarColor: "#a78bfa",
  },
  {
    id: "n5",
    type: "campaign_invite",
    title: "New Campaign Invite",
    body: "NexTech Gear wants you for their NexPod Pro earbuds review campaign.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    read: true,
    actionPath: "/campaigns",
    avatarInitials: "NT",
    avatarColor: "#60a5fa",
  },
  {
    id: "n6",
    type: "system",
    title: "Pro Plan Expiring Soon",
    body: "Your Pro plan trial ends in 3 days. Upgrade to keep your full access.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    read: true,
    actionPath: "/subscription",
    avatarInitials: "SY",
    avatarColor: "#6366f1",
  },
  {
    id: "n7",
    type: "payment",
    title: "Pending Payout",
    body: "NexTech Gear's payment of $850 is currently pending. Expected in 3 business days.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    read: true,
    actionPath: "/transactions",
    avatarInitials: "NT",
    avatarColor: "#60a5fa",
  },
];
