import type { Transaction } from "../../../components/dashboard/types";

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "t1",
    description: "GlowUp Beauty — Campaign Payout",
    brand: "GlowUp Beauty",
    amount: 3000,
    type: "credit",
    date: "2026-03-01",
    status: "completed",
  },
  {
    id: "t2",
    description: "Aura Coffee — Milestone Payment",
    brand: "Aura Coffee",
    amount: 300,
    type: "credit",
    date: "2026-03-10",
    status: "completed",
  },
  {
    id: "t3",
    description: "Pro Plan — Monthly Subscription",
    amount: 29,
    type: "debit",
    date: "2026-03-15",
    status: "completed",
  },
  {
    id: "t4",
    description: "SolarWave Tech — Advance Payment",
    brand: "SolarWave Tech",
    amount: 900,
    type: "credit",
    date: "2026-02-20",
    status: "completed",
  },
  {
    id: "t5",
    description: "Platform Fee (2%)",
    amount: 78,
    type: "debit",
    date: "2026-03-01",
    status: "completed",
  },
  {
    id: "t6",
    description: "NexTech Gear — Campaign Payout",
    brand: "NexTech Gear",
    amount: 850,
    type: "credit",
    date: "2026-02-10",
    status: "pending",
  },
  {
    id: "t7",
    description: "Pro Plan — Monthly Subscription",
    amount: 29,
    type: "debit",
    date: "2026-02-15",
    status: "completed",
  },
  {
    id: "t8",
    description: "Withdrawal to GTBank",
    amount: 2000,
    type: "debit",
    date: "2026-03-20",
    status: "completed",
  },
];
